### ISSUE TITLE
Assertion failed in security.cpp

### ISSUE THREAD

**Issue by caresx** [po-devs/pokemon-online#1209]
Posting this for a friend, this happened randomly:

![](http://i.imgur.com/sobIRm2.png)

I recall this happening to @Ethan when he hosted a server for our community, also randomly, usually after the server has been up for a few hours.

If you accept the dialog the server closes, of course. If you don't the server window is frozen (but the server is still running fine).

[This](https://github.com/po-devs/pokemon-online/blob/b8219c7253e7d390bd30d10ede5156199952d922/src/Server/security.cpp#L321-L334) seems to be the code in question.

It might be related to our [scripts](https://github.com/meteor-falls/Scripts), but either way still a bug.

**Comment by Fuzzysqurl** [comment]
https://github.com/po-devs/pokemon-online/commit/47ee873c4202c7b377d19e88beff6067571c4717 no more assertion errors. Someone else had this issue too on the forums and they said after a week of using this commit nothing happened incorrectly and the server has been stable.
