### ISSUE TITLE
Make client scripts support several scripts at the same time

### ISSUE THREAD

**Issue by coyotte508** [po-devs/pokemon-online#137]
So that a user can load several scripts (like a friend script, etc.) without hassle.

Maybe make a hard-coded limit of 4 if you want the easy way with tabs and the ui (because 4 has to be enough). Or unlimited with a neat interface.

Anyway, it's easy, there's no problems coming from having several scripts at the same time (just treat it like separate client plugins, and you'll see there's no problem)

**Comment by NightfallAlicorn** [comment]
The older tabs thing hasn't been fixed yet. Where you open 2, upload a script, tab 2 updates but tab 1 doesn't. :x The only issue I'm thinking of is scripts clashing with each other, I know TheUnknownOne made a script load that runs multiple scripts at once. Maybe under the tab client and battle tab in script window, add like 3 slots you can name that remembers like script1, script2 and script3.same with battlescripts.
