### ISSUE TITLE
Battleserver crash

### ISSUE THREAD

**Issue by CrystalMoogle** [po-devs/pokemon-online#1388]
https://github.com/po-devs/pokemon-online/blame/master/src/BattleServer/battle.cpp#L3871

This line causes a crash when player == 3. I don't know how player gets defined to 3, but I'm assuming it's related to all the changes done to poke. 3 crashes earlier today, all had player defined as 3.

Here's the full backtrace 
![backtrace](https://cloud.githubusercontent.com/assets/1566177/7418622/19582540-ef67-11e4-9042-53d7ab6255cc.png)

Note that the line numbers don't match 100% to repo's since the repo has been updated recently.

**Comment by CrystalMoogle** [comment]
Another 2 today, this time player was 4 in one of them

**Comment by CrystalMoogle** [comment]
Another crash related to this. I think lines battle.cpp:926 and 929 need changing the same way as the previous line, but I'm sleeping now, so I don't really want to deal with testing now

**Comment by coyotte508** [comment]
Lines 926 and 929 wouldn't need changing, there is `int player = this->player(slot);` at line 922. Having a backtrace would be great.

**Comment by CrystalMoogle** [comment]
Oh I completely forgot about this. But yeah you're right, I didn't really pay much attention, I was annoyed because people kept bothering me about the crash right when I was going to sleep.
Anyway, BT

![fdix40j 1](https://cloud.githubusercontent.com/assets/1566177/7638744/c96011d4-fa6e-11e4-9bdf-6d2496e31e5a.png)
