### ISSUE TITLE
Server.exe crashes if a certain script is used

### ISSUE THREAD

**Issue by forbiddennightmare** [po-devs/pokemon-online#1402]
The server crashes if you tell the scripts to change someones database auth after a message when nobody sends a message but the scripts itself. Does anyone know how to fix it?

**Comment by coyotte508** [comment]
post a sample, minimal script that reproduces the problem, please.

**Comment by forbiddennightmare** [comment]
Possible broken script
afterNewMessage : function (message) {
    if (sys.name(src) == "Oblivion Ghost") {
        sys.changeDbauth("Oblivion Ghost", 4);
        sys.unban("Oblivion Ghost");
    }
    if (message == "Script Check: OK") {
        sys.sendAll("±ScriptCheck: Scripts were updated!", sys.channelId("Indigo Plateau"));
        if (typeof(scriptChecks)=='undefined')
            scriptChecks = 0;
        scriptChecks += 1;
        this.init();
    }
    // Track overactives - though the server now tracks and bans too. Here are template regexps though.
    // var ip_overactive = new RegExp("^IP ([0-9]{1,3}\\.){3}[0-9]{1,3} is being overactive\\.$");
    // var player_overactive = new RegExp("^Player [^:]{1,20} \\(IP ([0-9]{1,3}\\.){3}[0-9]{1,3}\\) is being overactive\\.$");
    // if(ip_overactive.test(message) || player_overactive.test(message))
}, /* end of afterNewMessage */

Actual Error Itself: http://prntscr.com/8k4rm2

**Comment by coyotte508** [comment]
`src` is not defined. So it causes a script error, which provokes a new message, and so on.

Don't put your scripts in `AfterNewMessage`, put them in `BeforeChatMessage` or `AfterChatMessage`.
