### ISSUE TITLE
Change Session Handler Error print out?

### ISSUE THREAD

**Issue by Fuzzysqurl** [po-devs/pokemon-online#1413]
Currently our code to print a session handler error is as follows:
```c++
void SessionDataFactory::checkError()
{
    if (scriptEngine->hasUncaughtException()) {
        engine->printLine(QString("Session handler error: line %1. %2").arg(
            QString::number(scriptEngine->uncaughtExceptionLineNumber())
        ).arg(scriptEngine->uncaughtException().toString()));
    }
}
```

But this doesn't always give enough information to solve what might be causing it. What about changing it to the following:
```c++
void SessionDataFactory::checkError()
{
    if (scriptEngine->hasUncaughtException()) {
        engine->printLine(QString("Session handler error: %1.").arg(scriptEngine->uncaughtExceptionBacktrace().join(" ")));
    }
}
```

Documentation for uncaughtExceptionBacktrace()
```
QStringList QScriptEngine::uncaughtExceptionBacktrace() const

Returns a human-readable backtrace of the last uncaught exception.
It is in the form <function-name>()@<file-name>:<line-number>.
```

I'd assume we'd be able to get a little more information about the error to address it. There was recently a session handler error with Channel Mutes/Bans following an update and it took us a little bit of time to solve the issue. Now there's a completely different issue appearing  (``Session handler error: line 237. TypeError: Result of expression 'commandData' [undefined] is not an object.``) and we have no idea what is causing it.

Obviously I have no idea what would break or change by implementing this, so I'm creating an issue to discuss a possibility. Also, Script Warnings include a backtrace, but Session Errors do not.

**Comment by coyotte508** [comment]
why not?

**Comment by Fuzzysqurl** [comment]
So I decided to actually test this the way I presented it here and it just returned "." for all the errors. Back to the drawing board.
