### ISSUE TITLE
g++: error: Stuff\pokemon-online-master\src\Shared\..\..\bin\libpo-utilities.a: No such file or directory

### ISSUE THREAD

**Issue by Arburator** [po-devs/pokemon-online#1451]
Makefile.Release:154: recipe for target '..\..\..\..\pokemon-online-master\bin\po-utilities.dll' failed
mingw32-make[3]: *** [..\..\..\..\pokemon-online-master\bin\po-utilities.dll] Error 1
mingw32-make[3]: Leaving directory 'C:/Users/ryan/Desktop/PO Stuff/build-PokemonOnline-Desktop_Qt_5_0_2_MinGW_32bit-Release/src/libraries/Utilities'
Makefile:34: recipe for target 'release' failed
mingw32-make[2]: Leaving directory 'C:/Users/ryan/Desktop/PO Stuff/build-PokemonOnline-Desktop_Qt_5_0_2_MinGW_32bit-Release/src/libraries/Utilities'
mingw32-make[2]: *** [release] Error 2
Makefile:41: recipe for target 'sub-Utilities-make_first-ordered' failed
mingw32-make[1]: *** [sub-Utilities-make_first-ordered] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/ryan/Desktop/PO Stuff/build-PokemonOnline-Desktop_Qt_5_0_2_MinGW_32bit-Release/src/libraries'
makefile:39: recipe for target 'sub-src-libraries-make_first-ordered' failed
mingw32-make: *** [sub-src-libraries-make_first-ordered] Error 2
10:19:40: The process "C:\Qt\Qt5.0.2\Tools\MinGW\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project PokemonOnline (kit: Desktop Qt 5.0.2 MinGW 32bit)
When executing step 'Make'
10:19:40: Elapsed time: 00:02.

**Comment by turbedi** [comment]
Try to rename the folder /PO Stuff/ so that it doesn't contain a whitespace anymore (e.g. POStuff).

**Comment by SteveC688** [comment]
Your idiocy is not a PO bug. Please stop posting dumb "issues" like these or you will be blocked. The forums can be used for help.
