### ISSUE TITLE
Triple Kick in generation 2 doesn't do accuracy checks but does in PO

### ISSUE THREAD

**Issue by FredrIQ** [po-devs/pokemon-online#1622]
It rather just hits between 1-3 times at random, with an even distribution.

In pret's source, see effect_commands.asm @ BattleCommand_EndLoop. Relevant code pasted below with comments by me to clarify what it does:

    BattleCommand_EndLoop:
            ...
            cp EFFECT_TRIPLE_KICK
            jr nz, .not_triple_kick
    .reject_triple_kick_sample
            ; Get a random number between 0-2
            call BattleRandom
            and $3
            jr z, .reject_triple_kick_sample
            dec a

            ; If the result is between 1-2, do 2-3 hits (double_hit gives hit count as a+1)
            jr nz, .double_hit

            ; otherwise, just do 1 hit, meaning we're done here
            ld a, 1
            ld [bc], a
            jr .done_loop
            ...
    .double_hit
            ld [de], a
            inc a
            ld [bc], a
            jr .loop_back_to_critical
            ...

**Comment by turbedi** [comment]
To sum it up: hitcount = random number between 1 and 3 , right?

**Comment by FredrIQ** [comment]
Yep

**Comment by turbedi** [comment]
Fixed
