### ISSUE TITLE
Alolan formes in tiers and sys.isAestheric

### ISSUE THREAD

**Issue by CrystalMoogle** [po-devs/pokemon-online#1623]
> [3:59 PM] Ripper Roo: sys.isPokeBannedFromTier returns incorrect results for alolan formes
> [4:04 PM] Zana: Weird, it's a simple string comparasion
> [4:04 PM] Zana: Either names aren't returned right from id or the formes names aren't saved right in the tiers
> [7:45 PM] Zana: wait i see the issue
> [7:45 PM] Zana: Why are Alolan pokemon tiered the same as their base form?
> [7:47 PM] Zana: (19:47:05) The Pokemon 'Alolan Raichu' is banned on tier 'SM OU' for the following reasons: Pokemon Alolan Raichu is banned.
> [7:47 PM] Zana: But I only banned normal Raichu
> February 22, 2017
> [4:51 AM] Ripper Roo: :v
> [4:51 AM] Ripper Roo: while we're on that, sys.isAesthetic considers things like the therian formes as aesthetic which is inaccurate
> [8:25 AM] Ripper Roo: therians, deoxys, shaymin, giratina, arceus, genesect, pumpkaboo, gourgeist, zygarde 10%, silvally(edited)
> [8:25 AM] Ripper Roo: forms incorrectly stated as aesthetic
> [8:26 AM] Zana: Huh
> [8:27 AM] Zana: Deoxys formes work fine though in tiers
> [8:27 AM] Zana: And that just uses aesthetic forme check
> [8:28 AM] Ripper Roo: well maybe im just using it wrong :x
> [8:28 AM] Ripper Roo: does it accept the base form or the actual form?
> [8:29 AM] Zana: Idk about the isAesthetic function
> [8:29 AM] Zana: But you can ban Deoxys
> [8:29 AM] Zana: But have the formes unbanned
> [8:30 AM] Zana: And tiers just aesthetic forme to check if base forme should ban alt formes
> [8:30 AM] Ripper Roo: oh
> [8:31 AM] Ripper Roo: well that explains why all the above forms happen to have their own usage
> [8:34 AM] Ripper Roo: its going to be dumb trying to use it the way it is for /pokemon though
> [8:34 AM] Ripper Roo: lando-t is considered an aesthetic of lando-i and will appear to be banned from OU
> [8:34 AM] Ripper Roo: etc
> [8:38 AM] Zana: Well it should be this way
> [8:38 AM] Zana: Shouldn't
> [8:38 AM] Zana: If it's a forme that you can switch outside of battle and has different types/stats, it should be counted as a different Pokemon on tiers
> [8:40 AM] Ripper Roo: yeah, so I can't rely on isAesthetic for those formes :x
> maybe I'll just hard code them into the command itself
> [12:00 PM] Zana: Lol
> [12:01 PM] Zana: Amazing
> [12:01 PM] Zana: I see
> [12:01 PM] Zana: Someone turned all formes into aesthetic formes at some point
> [12:01 PM] Zana: Wtf
> [12:10 PM] Zana: To fix alolan formes you'd need to add AD flags to them
> [12:10 PM] Zana: To fix isAesthetic you'd have to make it look for D flag as well

Someone probably read it in discord and might be fixing it, but whatever. I'm not doing it myself because I'm too lazy to download stuff to test. Either you need to do what I suggested there, or revert all formes being aesthetic for whatever reason.

**Comment by turbedi** [comment]
I am still busy with exams right now, so I can't look into it atm.
Gonna be back starting next Monday. I will look into it isn't fixed until then

**Comment by CrystalMoogle** [comment]
sys.isDifferent works instead of sys.isAesthetic
I'm still not really sure why that needs to be separate commands, since isAesthetic should mean no stat/type/moveset changes but whatever
