### ISSUE TITLE
Add event specification on login

### ISSUE THREAD

**Issue by coyotte508** [po-devs/pokemon-online#46]
http://wiki.pokemon-online.eu/view/Network_Protocol_v2

**Comment by NightfallAlicorn** [comment]
That link is empty, you mean:
https://github.com/po-devs/pokemon-online/wiki/po:-Protocol
or
https://github.com/po-devs/pokemon-online/wiki/Client-Scripts%3A-Network-object
?

I could try add more stuff to the Wiki if you want?

**Comment by CrystalMoogle** [comment]
He's talking about
https://github.com/po-devs/pokemon-online/wiki/Network-Protocol
On 22 Jul 2015 4:50 pm, "NightfallAlicorn" <notifications@github.com> wrote:
>
> That link is empty, you mean:
> https://github.com/po-devs/pokemon-online/wiki/po:-Protocol
> or
>
https://github.com/po-devs/pokemon-online/wiki/Client-Scripts%3A-Network-object
