### ISSUE TITLE
Sp. Attack and Sp. Defense instead of Special in the teambuilder.

### ISSUE THREAD

**Issue by turbedi** [po-devs/pokemon-online#722]
When I select Gen 1 and replace Missingno with another pokémon, PO shows Sp. Attack and Sp. Defense instead of Special.
Replace Missingno with another pokémon: http://i43.tinypic.com/9zrqmp.png
Replace a random pokémon: http://i40.tinypic.com/2z9ilpd.png

**Comment by coyotte508** [comment]
Can't reproduce.

**Comment by turbedi** [comment]
It still happens for me. Are you sure you tried to replace Missingno?

**Comment by coyotte508** [comment]
yes.
